output "scaling_plan_id" {
  description = "Resource ID of the AVD scaling plan."
  value       = azurerm_virtual_desktop_scaling_plan.this.id
}

output "scaling_plan_name" {
  description = "Name of the AVD scaling plan, as generated by the naming module."
  value       = azurerm_virtual_desktop_scaling_plan.this.name
}

output "personal_schedule_ids" {
  description = "Map of personal schedule key -> resource ID (azapi)."
  value       = { for k, v in azapi_resource.personal_schedule : k => v.id }
}
