output "vwan_id" {
  description = "Resource ID of the Virtual WAN. Consumed by both hub modules (Hub01 secured, Hub02 unsecured)."
  value       = azurerm_virtual_wan.this.id
}

output "vwan_name" {
  description = "Name of the Virtual WAN, as generated by the naming module."
  value       = azurerm_virtual_wan.this.name
}
