output "storage_account_id" {
  description = "Resource ID of the FSLogix storage account."
  value       = azurerm_storage_account.this.id
}

output "storage_account_name" {
  description = "Name of the FSLogix storage account, as generated by the naming module."
  value       = azurerm_storage_account.this.name
}

output "primary_file_host" {
  description = "Primary file service host (e.g. <account>.file.core.windows.net)."
  value       = azurerm_storage_account.this.primary_file_host
}

output "file_share_names" {
  description = "List of file share names created by this module."
  value       = [for s in azurerm_storage_share.this : s.name]
}

output "file_share_urls" {
  description = "Map of share name -> share URL."
  value       = { for k, v in azurerm_storage_share.this : k => v.url }
}
