# Auto-ported from legacy images/.../params/gallery/configSets.json galleryStandard (50 defs)
locals {
  image_definitions = {
    "windows-desktop-11-gen2-22h2ent-mult-tl-000" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-000" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-001" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-001" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-002" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-002" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-003" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-003" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-004" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-004" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-005" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-005" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-006" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-006" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-007" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-007" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-008" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-008" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-009" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-009" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-010" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-010" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-888" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-888" }
    "windows-desktop-11-gen2-22h2ent-mult-tl-999" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-22h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-22h2ent-mult-tl-999" }
    "linux-cis-server-2004-gen2-lts-vdiazdoagent" = { os_type = "Linux", hyper_v_generation = "V2", security_type = "Standard", identifier = { publisher = "canonical", offer = "0001-com-ubuntu-pro-minimal-cis-focal", sku = "pro-cis-minimal-20_04-gen2" }, legacy_name = "img-linux-cis-server-2004-gen2-lts-vdiazdoagent" }
    "linux-minimal-server-2404-lts-vdiazdoagent" = { os_type = "Linux", hyper_v_generation = "V2", security_type = "Standard", identifier = { publisher = "canonical", offer = "ubuntu-24_04-lts", sku = "minimal" }, legacy_name = "img-linux-minimal-server-2404-lts-vdiazdoagent" }
    "windows-desktop-11-gen2-23h2ent-base" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-11", sku = "win11-23h2-ent" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-base" }
    "windows-desktop-11-gen2-23h2ent-base-priv" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-11", sku = "win11-23h2-ent" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-base-priv" }
    "windows-desktop-11-gen2-24h2ent-base-priv" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-11", sku = "win11-24h2-ent" }, legacy_name = "img-windows-desktop-11-gen2-24h2ent-base-priv" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-000" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-000" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-001" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-001" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-002" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-002" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-003" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-003" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-004" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-004" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-005" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-005" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-006" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-006" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-007" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-007" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-008" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-008" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-009" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-009" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-010" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-010" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-888" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-888" }
    "windows-desktop-11-gen2-23h2ent-mult-tl-999" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-23h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-23h2ent-mult-tl-999" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-000" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-000" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-001" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-001" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-002" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-002" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-003" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-003" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-004" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-004" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-005" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-005" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-006" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-006" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-007" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-007" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-008" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-008" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-009" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-009" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-010" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-010" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-888" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-888" }
    "windows-desktop-11-gen2-25h2ent-mult-tl-999" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "office-365", sku = "win11-25h2-avd-m365" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-mult-tl-999" }
    "windows-desktop-10-gen2-21h2ent-base-tl" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-10", sku = "win10-21h2-ent" }, legacy_name = "img-windows-desktop-10-gen2-21h2ent-base-tl" }
    "windows-desktop-11-gen2-24h2ent-base-packaging" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-11", sku = "win11-24h2-ent" }, legacy_name = "img-windows-desktop-11-gen2-24h2ent-base-packaging" }
    "windows-desktop-11-gen2-24h2ent-base" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-11", sku = "win11-24h2-ent" }, legacy_name = "img-windows-desktop-11-gen2-24h2ent-base" }
    "windows-desktop-11-gen2-25h2ent-base-packaging" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-11", sku = "win11-25h2-ent" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-base-packaging" }
    "windows-desktop-11-gen2-25h2ent-base-priv" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-11", sku = "win11-25h2-ent" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-base-priv" }
    "windows-desktop-11-gen2-25h2ent-base" = { os_type = "Windows", hyper_v_generation = "V2", security_type = "TrustedLaunch", identifier = { publisher = "MicrosoftWindowsDesktop", offer = "windows-11", sku = "win11-25h2-ent" }, legacy_name = "img-windows-desktop-11-gen2-25h2ent-base" }
  }
}

