output "hub_id" {
  description = "Resource ID of the unsecured virtual hub. Consumed by MSH spoke modules for hub connections."
  value       = azurerm_virtual_hub.this.id
}

output "hub_name" {
  description = "Name of the unsecured virtual hub, as generated by the naming module."
  value       = azurerm_virtual_hub.this.name
}

output "vpn_gateway_id" {
  description = "Resource ID of the VPN Gateway. Consumed by MSH spoke modules for internet egress via the Palo Alto Proxy."
  value       = azurerm_vpn_gateway.this.id
}
