output "law_id" {
  description = "Resource ID of the Log Analytics workspace. Consumed by all other modules for diagnostic settings."
  value       = azurerm_log_analytics_workspace.this.id
}

output "law_workspace_id" {
  description = "Workspace (customer) ID / GUID of the Log Analytics workspace."
  value       = azurerm_log_analytics_workspace.this.workspace_id
}

output "law_name" {
  description = "Name of the Log Analytics workspace, as generated by the naming module."
  value       = azurerm_log_analytics_workspace.this.name
}

output "data_collection_endpoint_id" {
  description = "Resource ID of the Data Collection Endpoint, or null when not created."
  value       = var.create_data_collection_endpoint ? azurerm_monitor_data_collection_endpoint.this[0].id : null
}

output "avd_insights_dcr_id" {
  description = "Resource ID of the AVD Insights Data Collection Rule, or null when not created."
  value       = var.create_avd_insights_dcr ? azurerm_monitor_data_collection_rule.avd[0].id : null
}

output "action_group_ids" {
  description = "Map of action group key -> resource ID."
  value       = { for k, v in azurerm_monitor_action_group.this : k => v.id }
}
