output "keyvault_id" {
  description = "Resource ID of the Key Vault."
  value       = azurerm_key_vault.this.id
}

output "keyvault_uri" {
  description = "Data-plane URI of the Key Vault."
  value       = azurerm_key_vault.this.vault_uri
}

output "keyvault_name" {
  description = "Name of the Key Vault, as generated by the naming module."
  value       = azurerm_key_vault.this.name
}

output "cmk_key_ids" {
  description = "Map of key name -> versionless key ID. Consumed by services needing a CMK (e.g. storage, disks)."
  value       = { for k, v in azurerm_key_vault_key.this : k => v.versionless_id }
}
