output "workspace_id" {
  description = "Resource ID of the AVD workspace."
  value       = azurerm_virtual_desktop_workspace.this.id
}

output "workspace_name" {
  description = "Name of the AVD workspace, as generated by the naming module."
  value       = azurerm_virtual_desktop_workspace.this.name
}

output "app_group_ids" {
  description = "Map of application group key -> resource ID."
  value       = { for k, v in azurerm_virtual_desktop_application_group.this : k => v.id }
}
