output "image_definition_id" {
  description = "Resource ID of the image definition. Consumed by Packer pipelines to publish versions."
  value       = azurerm_shared_image.this.id
}

output "image_definition_name" {
  description = "Name of the image definition, as generated by the naming module. Used in Packer .pkr.hcl variable files."
  value       = azurerm_shared_image.this.name
}
