output "policy_id" {
  description = "Resource ID of the firewall policy. Passed to modules/platform/hub-secured as firewall_policy_id."
  value       = azurerm_firewall_policy.this.id
}

output "policy_name" {
  description = "Name of the firewall policy, as generated by the naming module."
  value       = azurerm_firewall_policy.this.name
}

output "ip_group_ids" {
  description = "Map of IP group key -> resource ID for all IP groups created by this module."
  value       = { for k, v in azurerm_ip_group.this : k => v.id }
}
