output "gallery_id" {
  description = "Resource ID of the compute gallery. Consumed by the image-definition module and Packer pipelines."
  value       = azurerm_shared_image_gallery.this.id
}

output "gallery_name" {
  description = "Name of the compute gallery, as generated by the naming module."
  value       = azurerm_shared_image_gallery.this.name
}
